import { Treatment } from "./types"

export const treatments: Treatment[] = [
    {
        id: "tx-001",
        name: "GLP-1 Receptor Agonists",
        category: "Diabetes",
        type: "Medication",
        description: "Injectable medications that help regulate blood sugar by mimicking the GLP-1 hormone. Includes options like semaglutide and tirzepatide.",
        detailedProcedure: "Self-administered subcutaneous injection once per week using a pre-filled pen. Injection sites typically include the abdomen, thigh, or upper arm.",
        recoveryTime: "No recovery time needed; immediate return to daily activities.",
        successRate: 85,
        duration: "Ongoing treatment",
        costEstimate: "$800-1500/month",
        benefits: ["Significant weight loss", "Improved blood sugar control", "Cardiovascular protection", "Once-weekly dosing available"],
        risks: ["Gastrointestinal side effects", "Rare thyroid concerns", "Pancreatitis risk"],
        sideEffects: ["Nausea", "Vomiting", "Diarrhea", "Constipation"],
        precautions: ["Monitor for severe abdominal pain", "Stay hydrated", "Regular kidney function monitoring"],
        alternatives: [
            { name: "SGLT2 inhibitors", id: "tx-007" },
            { name: "DPP-4 inhibitors", id: "tx-008" },
            { name: "Insulin therapy", id: "tx-009" }
        ],
        conditions: ["Type 2 Diabetes", "Obesity", "Pre-diabetes"],
        aiInsight: "Based on recent clinical data, GLP-1 agonists show 20-30% better outcomes for patients with concurrent cardiovascular disease compared to traditional therapies.",
    },
    {
        id: "tx-002",
        name: "Immunotherapy (PD-1/PD-L1 Inhibitors)",
        category: "Oncology",
        type: "Medication",
        description: "Checkpoint inhibitors that help the immune system recognize and attack cancer cells. Includes pembrolizumab, nivolumab, and others.",
        detailedProcedure: "Intravenous infusion administered in a clinical setting every 2-6 weeks depending on the specific drug and protocol.",
        recoveryTime: "1-2 days of rest post-infusion to monitor for immediate reactions.",
        successRate: 45,
        duration: "6-24 months typically",
        costEstimate: "$12,000-20,000/month",
        benefits: ["Durable responses", "Works across multiple cancer types", "May lead to long-term remission", "Better quality of life than chemo"],
        risks: ["Immune-related adverse events", "Pneumonitis", "Colitis", "Hepatitis"],
        sideEffects: ["Fatigue", "Skin rash", "Diarrhea", "Thyroid dysfunction"],
        precautions: ["Frequent blood tests for organ function", "Report any new shortness of breath", "Monitor for severe skin reactions"],
        alternatives: [
            { name: "Chemotherapy", id: "tx-010" },
            { name: "Targeted Therapy", id: "tx-011" },
            { name: "Radiation Therapy", id: "tx-012" }
        ],
        conditions: ["Non-Small Cell Lung Cancer", "Melanoma", "Renal Cell Carcinoma", "Bladder Cancer"],
        aiInsight: "Patients with high PD-L1 expression (>50%) show response rates up to 60%. Biomarker testing is recommended before treatment initiation.",
    },
    {
        id: "tx-003",
        name: "Cognitive Behavioral Therapy (CBT)",
        category: "Mental Health",
        type: "Therapy",
        description: "Structured psychotherapy that helps identify and change negative thought patterns and behaviors. Effective for anxiety, depression, and other conditions.",
        detailedProcedure: "Weekly 50-60 minute sessions with a licensed therapist, involving cognitive restructuring, behavioral experiments, and home assignments.",
        recoveryTime: "No physical recovery; mental and emotional processing time varies.",
        successRate: 75,
        duration: "12-20 weeks typically",
        costEstimate: "$100-250/session",
        benefits: ["No medication side effects", "Long-lasting results", "Teaches coping skills", "Can be combined with medication"],
        risks: ["Requires commitment", "May initially increase distress", "Results vary"],
        sideEffects: ["Temporary emotional discomfort", "Time commitment required"],
        precautions: ["Ensure professional licensure of provider", "Consistency is key for efficacy", "Be open about distress levels"],
        alternatives: [
            { name: "SSRI Medication", id: "tx-013" },
            "Dialectical Behavior Therapy",
            "Mindfulness-based therapy"
        ],
        conditions: ["Depression", "Anxiety Disorders", "PTSD", "OCD", "Insomnia"],
        aiInsight: "CBT combined with medication shows 30% better outcomes for moderate-to-severe depression compared to either treatment alone.",
    },
    {
        id: "tx-004",
        name: "Transcatheter Aortic Valve Replacement (TAVR)",
        category: "Cardiovascular",
        type: "Procedure",
        description: "Minimally invasive procedure to replace a narrowed aortic valve without open-heart surgery.",
        detailedProcedure: "A catheter is inserted through the femoral artery in the groin and guided to the heart to place the new valve within the old one.",
        recoveryTime: "3-5 days in hospital, followed by 1-2 weeks of light activity at home.",
        successRate: 95,
        duration: "1-2 hour procedure, 3-5 day recovery",
        costEstimate: "$50,000-80,000",
        benefits: ["Minimally invasive", "Faster recovery", "Lower surgical risk", "Suitable for high-risk patients"],
        risks: ["Stroke", "Vascular complications", "Pacemaker requirement", "Valve leak"],
        sideEffects: ["Temporary fatigue", "Soreness at access site", "Irregular heartbeat"],
        precautions: ["Strict monitoring for groin site bleeding", "Regular follow-up echoes", "Endocarditis prophylaxis"],
        alternatives: [
            { name: "Open Heart Surgery (SAVR)", id: "tx-015" },
            "Balloon valvuloplasty",
            "Medical management"
        ],
        conditions: ["Aortic Stenosis", "Aortic Valve Disease"],
        aiInsight: "For patients over 70, TAVR shows similar long-term outcomes to surgical replacement with significantly shorter hospital stays.",
    },
    {
        id: "tx-005",
        name: "Deep Brain Stimulation (DBS)",
        category: "Neurology",
        type: "Device",
        description: "Surgical implant of electrodes in specific brain areas to deliver electrical stimulation for movement disorders.",
        detailedProcedure: "Two-stage surgery: 1) Placement of electrodes in the brain while awake/sedated. 2) Placement of the impulse generator (IPG) under the chest skin under general anesthesia.",
        recoveryTime: "2-4 weeks post-surgery for healing, followed by several months of device programming and adjustment.",
        successRate: 70,
        duration: "Permanent implant, battery replacement every 3-5 years",
        costEstimate: "$35,000-100,000",
        benefits: ["Significant symptom reduction", "Adjustable settings", "Reduces medication needs", "Reversible"],
        risks: ["Surgical complications", "Infection", "Hardware issues", "Speech problems"],
        sideEffects: ["Tingling sensations", "Mood changes", "Balance issues during adjustment"],
        precautions: ["Avoid strong electromagnetic fields (MRI restricts)", "Regular battery checks", "Report any skin erosion over hardware"],
        alternatives: ["Medication optimization", "Physical therapy", "Focused ultrasound", "Lesioning surgery"],
        conditions: ["Parkinson's Disease", "Essential Tremor", "Dystonia", "OCD"],
        aiInsight: "Patients who receive DBS within 7 years of Parkinson's diagnosis show better motor outcomes than those treated later in disease progression.",
    },
    {
        id: "tx-006",
        name: "Mediterranean Diet Protocol",
        category: "Cardiovascular",
        type: "Lifestyle",
        description: "Evidence-based dietary pattern emphasizing olive oil, fish, nuts, fruits, vegetables, and whole grains.",
        detailedProcedure: "Sustainable shift in daily food choices: high intake of healthy fats (EVOO), plant-based proteins, and limit on red meats and processed sugars.",
        recoveryTime: "Immediate; however, metabolic adaptation may take 4-8 weeks.",
        successRate: 65,
        duration: "Lifelong lifestyle change",
        costEstimate: "$50-100/week additional",
        benefits: ["Heart disease risk reduction", "Weight management", "Anti-inflammatory effects", "Cognitive benefits"],
        risks: ["Requires dietary changes", "May not suit all preferences"],
        sideEffects: ["Initial adjustment period", "Increased cooking time"],
        precautions: ["Ensure adequate protein intake", "Watch caloric density of oils/nuts", "Regular lipid profile monitoring"],
        alternatives: [
            { name: "DASH Diet Protocol", id: "tx-014" },
            "Plant-based diet",
            "Low-carb diet"
        ],
        conditions: ["Heart Disease", "Hypertension", "Type 2 Diabetes", "Cognitive Decline Prevention"],
        aiInsight: "Studies show 30% reduction in cardiovascular events for high-risk patients following Mediterranean diet with extra virgin olive oil supplementation.",
    },
    {
        id: "tx-007",
        name: "SGLT2 inhibitors",
        category: "Diabetes",
        type: "Medication",
        description: "Oral medications that help the kidneys lower blood glucose by removing it through urine.",
        detailedProcedure: "Daily oral tablet taken once in the morning, with or without food.",
        recoveryTime: "Immediate; no downtime required.",
        successRate: 80,
        duration: "Ongoing treatment",
        costEstimate: "$400-600/month",
        benefits: ["Lower blood pressure", "Weight loss", "Heart failure risk reduction", "Kidney protection"],
        risks: ["Urinary tract infections", "Genital yeast infections", "Dehydration risk", "Ketoacidosis (rare)"],
        sideEffects: ["Increased urination", "Thirst", "Lightheadedness"],
        precautions: ["Maintain high fluid intake", "Monitor for signs of UTI", "Check blood pressure regularly"],
        alternatives: [{ name: "GLP-1 agonists", id: "tx-001" }, "Metformin"],
        conditions: ["Type 2 Diabetes", "Heart Failure", "Chronic Kidney Disease"],
        aiInsight: "SGLT2 inhibitors are now considered 'foundational therapy' for diabetic patients with heart failure regardless of glucose control.",
    },
    {
        id: "tx-008",
        name: "DPP-4 inhibitors",
        category: "Diabetes",
        type: "Medication",
        description: "Oral medications that block the DPP-4 enzyme to increase incretin hormones, which help lower blood sugar after meals.",
        detailedProcedure: "Daily oral tablet taken once per day at any time, with or without food.",
        recoveryTime: "Immediate; no downtime required.",
        successRate: 70,
        duration: "Ongoing treatment",
        costEstimate: "$300-500/month",
        benefits: ["Weight neutral", "Low risk of hypoglycemia", "Well-tolerated by elderly", "Simple dosing"],
        risks: ["Joint pain (reported in some studies)", "Skin reactions", "Naso-pharyngitis"],
        sideEffects: ["Headache", "Sore throat", "Upper respiratory tract infection"],
        precautions: ["Report severe or persistent joint pain", "Monitor for pancreatic symptoms", "Renal adjustment may be needed"],
        alternatives: [{ name: "GLP-1 agonists", id: "tx-001" }, { name: "SGLT2 inhibitors", id: "tx-007" }],
        conditions: ["Type 2 Diabetes"],
        aiInsight: "While well-tolerated, DPP-4 inhibitors generally show lower efficacy for weight loss compared to GLP-1 or SGLT2 classes.",
    },
    {
        id: "tx-009",
        name: "Insulin therapy",
        category: "Diabetes",
        type: "Medication",
        description: "Replacement of the body's natural insulin to regulate blood glucose directly.",
        detailedProcedure: "Subcutaneous self-injections using a pen or vial/syringe, or delivery via an insulin pump. Timing depends on the type (basal vs. bolus).",
        recoveryTime: "Immediate; requires continuous glucose monitoring.",
        successRate: 100,
        duration: "Ongoing, often lifelong",
        costEstimate: "$100-1000/month (varies wildly)",
        benefits: ["Precise glucose control", "Effective for all diabetes types", "Customizable dosing", "Prevents long-term complications"],
        risks: ["Hypoglycemia (low blood sugar)", "Weight gain", "Injection site lipodystrophy"],
        sideEffects: ["Hypoglycemic events", "Soreness at injection site", "Hunger"],
        precautions: ["Frequent finger-stick or CGM checks", "Always carry fast-acting glucose", "Rotate injection sites regularly"],
        alternatives: [{ name: "GLP-1 agonists", id: "tx-001" }, { name: "SGLT2 inhibitors", id: "tx-007" }],
        conditions: ["Type 1 Diabetes", "Type 2 Diabetes", "Gestational Diabetes"],
        aiInsight: "Modern smart insulin pens and CGMs have reduced hypoglycemic events by 40% compared to traditional manual dosing methods.",
    },
    {
        id: "tx-010",
        name: "Chemotherapy",
        category: "Oncology",
        type: "Medication",
        description: "Powerful drugs used to kill fast-growing cells in the body, primarily cancer cells.",
        detailedProcedure: "Cycles of intravenous infusions or oral pills, often requiring an implanted port for vascular access.",
        recoveryTime: "3-7 days of acute recovery per cycle; full recovery may take months after final treatment.",
        successRate: 50,
        duration: "3-6 months typically",
        costEstimate: "$5,000-15,000/cycle",
        benefits: ["Systemic treatment for metastatic disease", "Can shrink tumors before surgery", "Decades of clinical evidence"],
        risks: ["Infection risk (low white count)", "Hair loss", "Long-term organ damage", "Nerve damage"],
        sideEffects: ["Nausea", "Fatigue", "Hair thinning", "Mouth sores"],
        precautions: ["Avoid crowds to prevent infection", "Use soft toothbrush", "Report any fever over 100.4°F immediately"],
        alternatives: [
            { name: "Immunotherapy", id: "tx-002" },
            { name: "Targeted Therapy", id: "tx-011" },
            { name: "Radiation Therapy", id: "tx-012" }
        ],
        conditions: ["Various Cancers", "Leukemia", "Lymphoma"],
        aiInsight: "Newer anti-emetic medications have reduced severe chemotherapy-related nausea by over 70% in the last decade.",
    },
    {
        id: "tx-011",
        name: "Targeted Therapy",
        category: "Oncology",
        type: "Medication",
        description: "Drugs designed to target specific molecules (often proteins) that tell cancer cells to grow and divide.",
        detailedProcedure: "Daily oral pills or periodic intravenous infusions, depending on the specific target (e.g., EGFR, HER2, BRAF).",
        recoveryTime: "Minimal downtime; patients often maintain normal activity levels.",
        successRate: 55,
        duration: "Often continued as long as the cancer does not progress",
        costEstimate: "$8,000-15,000/month",
        benefits: ["Less damage to healthy cells", "Specifically tailored to tumor genetics", "Can be combined with other therapies"],
        risks: ["Development of drug resistance", "Skin issues", "High blood pressure", "Liver problems"],
        sideEffects: ["Rash", "Diarrhea", "Fatigue", "Nail changes"],
        precautions: ["Genetic profiling of tumor is mandatory", "Monitor liver enzymes regularly", "Strict adherence to daily dosing"],
        alternatives: [
            { name: "Immunotherapy", id: "tx-002" },
            { name: "Chemotherapy", id: "tx-010" }
        ],
        conditions: ["Breast Cancer", "Lung Cancer", "Colorectal Cancer", "Leukemia"],
        aiInsight: "Targeted therapies show a 40% higher progression-free survival rate in patients with specific genetic mutations compared to traditional chemo.",
    },
    {
        id: "tx-012",
        name: "Radiation Therapy",
        category: "Oncology",
        type: "Procedure",
        description: "High-energy particles or waves used to destroy or damage cancer cells in a specific area.",
        detailedProcedure: "Daily treatments (5 days a week) for 2-8 weeks. Patients lie under a machine (linear accelerator) for 15-30 minutes per session.",
        recoveryTime: "Ongoing recovery; fatigue often peaks 2 weeks after treatment ends.",
        successRate: 60,
        duration: "2-8 weeks",
        costEstimate: "$10,000-50,000 total",
        benefits: ["Localized treatment", "Non-invasive", "Preserves organ function", "Can provide pain relief (palliative)"],
        risks: ["Secondary cancers (rare)", "Radiation burns", "Tissue scarring (fibrosis)", "Infertility if targeting pelvis"],
        sideEffects: ["Fatigue", "Skin irritation", "Target-site pain"],
        precautions: ["Gentle skin care in treated area", "Avoid sun exposure to treated site", "Hydration is critical"],
        alternatives: [
            { name: "Chemotherapy", id: "tx-010" },
            "Surgery",
            "Brachytherapy"
        ],
        conditions: ["Localized Tumors", "Prostate Cancer", "Breast Cancer", "Brain Cancer"],
        aiInsight: "Intensity-Modulated Radiation Therapy (IMRT) has reduced damage to surrounding healthy tissue by nearly 50% compared to older techniques.",
    },
    {
        id: "tx-013",
        name: "SSRI Medication",
        category: "Mental Health",
        type: "Medication",
        description: "Selective Serotonin Reuptake Inhibitors used to increase serotonin levels in the brain to improve mood and anxiety.",
        detailedProcedure: "Daily oral tablet taken once per day. It usually takes 4-6 weeks to reach full therapeutic effect.",
        recoveryTime: "Immediate; no downtime required.",
        successRate: 60,
        duration: "6 months to several years",
        costEstimate: "$10-100/month",
        benefits: ["Widely available", "Effective for both anxiety and depression", "Low cost (many generics)", "Once-daily dosing"],
        risks: ["Serotonin syndrome (rare)", "Increased suicidal thoughts (in youth)", "Withdrawal symptoms if stopped abruptly"],
        sideEffects: ["Weight changes", "Sleep disturbance", "Sexual dysfunction", "Nausea"],
        precautions: ["Do not stop abruptly", "Avoid alcohol", "Monitor for mood changes in first 2 weeks"],
        alternatives: [
            { name: "Cognitive Behavioral Therapy (CBT)", id: "tx-003" },
            "SNRIs",
            "St. John's Wort (herbal)"
        ],
        conditions: ["Major Depression", "Generalized Anxiety", "Panic Disorder", "OCD"],
        aiInsight: "Pharmacogenomic testing can predict response to specific SSRIs with 75% accuracy, reducing the 'trial and error' phase of treatment.",
    },
    {
        id: "tx-014",
        name: "DASH Diet Protocol",
        category: "Cardiovascular",
        type: "Lifestyle",
        description: "Dietary Approaches to Stop Hypertension. Focuses on lowering sodium and eating nutrient-rich foods that lower blood pressure.",
        detailedProcedure: "Structured eating plan limiting sodium to 1500-2300mg/day and emphasizing potassium, calcium, and magnesium from whole foods.",
        recoveryTime: "Immediate; blood pressure reductions typically seen within 2 weeks.",
        successRate: 70,
        duration: "Lifelong lifestyle change",
        costEstimate: "Minimal additional cost",
        benefits: ["Significant blood pressure drop", "Reduces stroke risk", "Weight management", "Kidney protection"],
        risks: ["Requires careful food labeling reading", "Social dining challenges"],
        sideEffects: ["Initial flatulence from increased fiber", "Salt cravings during adjustment"],
        precautions: ["Monitor sodium intake strictly", "Regular blood pressure checks", "Gradual increase in fiber"],
        alternatives: [
            { name: "Mediterranean Diet Protocol", id: "tx-006" },
            "AHA Low Salt Diet",
            "Low-carb diet"
        ],
        conditions: ["Hypertension", "Pre-hypertension", "Heart Failure"],
        aiInsight: "The DASH diet has been shown to lower systolic blood pressure by 8-14 points, comparable to some single-drug antihypertensive therapies.",
    },
    {
        id: "tx-015",
        name: "Open Heart Surgery (SAVR)",
        category: "Cardiovascular",
        type: "Procedure",
        description: "Surgical Aortic Valve Replacement through a traditional sternotomy (opening the chest).",
        detailedProcedure: "Patient is placed on a heart-lung bypass machine while a surgeon removes the diseased valve and sews in a mechanical or biological replacement.",
        recoveryTime: "5-10 days in hospital, followed by 6-12 weeks of recovery at home.",
        successRate: 98,
        duration: "3-5 hour procedure",
        costEstimate: "$100,000-150,000",
        benefits: ["Highly durable results", "Gold standard for younger patients", "Lower risk of valve leak than TAVR"],
        risks: ["Infection", "Bleeding", "Heart rhythm issues", "Stroke"],
        sideEffects: ["Chest wall pain", "Fatigue", "Loss of appetite", "Mood swings"],
        precautions: ["Strict sternal precautions (lifting limits)", "Daily weight monitoring", "Cardiac rehabilitation is mandatory"],
        alternatives: [
            { name: "Transcatheter Aortic Valve Replacement (TAVR)", id: "tx-004" },
            "Medical management"
        ],
        conditions: ["Severe Aortic Stenosis", "Aortic Regurgitation"],
        aiInsight: "Mechanical valves used in SAVR can last over 25 years, making it the preferred choice for patients under 60 who can tolerate anticoagulation.",
    },
]
