import type { ClinicalTrial, MedicalCondition, Treatment } from "./types"

export const mockConditions: MedicalCondition[] = [
  {
    id: "1",
    name: "Type 2 Diabetes Mellitus",
    severity: "moderate",
    diagnosisDate: "2022-03-15",
    status: "managed",
    icdCode: "E11.9",
    description: "Chronic condition affecting blood sugar regulation",
  },
  {
    id: "2",
    name: "Hypertension",
    severity: "mild",
    diagnosisDate: "2021-08-20",
    status: "managed",
    icdCode: "I10",
    description: "Elevated blood pressure requiring ongoing management",
  },
  {
    id: "3",
    name: "Non-Small Cell Lung Cancer",
    severity: "severe",
    diagnosisDate: "2024-01-10",
    status: "active",
    icdCode: "C34.90",
    description: "Stage IIB adenocarcinoma, currently under treatment",
  },
]

export const mockTrials: ClinicalTrial[] = [
  {
    id: "1",
    nctId: "NCT05847392",
    title: "A Phase 3 Study of Novel Immunotherapy Combination for Advanced NSCLC",
    sponsor: "Memorial Sloan Kettering Cancer Center",
    phase: "Phase 3",
    status: "Recruiting",
    matchScore: 94,
    condition: "Non-Small Cell Lung Cancer",
    location: {
      city: "New York",
      state: "NY",
      country: "USA",
      facility: "Memorial Sloan Kettering Cancer Center",
      coordinates: { lat: 40.7643, lng: -73.9571 },
    },
    distance: "12 miles",
    eligibilityCriteria: {
      inclusion: [
        "Age 18 years or older",
        "Confirmed diagnosis of Stage IIB-IV NSCLC",
        "ECOG performance status 0-1",
        "Adequate organ function",
        "No prior immunotherapy treatment",
      ],
      exclusion: [
        "Active autoimmune disease",
        "Known brain metastases",
        "History of severe allergic reactions",
        "Concurrent malignancy",
      ],
    },
    description:
      "This study evaluates the efficacy and safety of a novel immunotherapy combination compared to standard chemotherapy in patients with advanced non-small cell lung cancer.",
    startDate: "2024-02-01",
    estimatedEndDate: "2026-12-31",
    enrollment: 450,
    primaryOutcome: "Progression-free survival at 12 months",
    secondaryOutcomes: [
      "Overall survival",
      "Objective response rate",
      "Duration of response",
    ],
    contactInfo: {
      name: "Dr. Sarah Chen",
      phone: "(212) 639-2000",
      email: "clinicaltrials@mskcc.org",
    },
  },
  {
    id: "2",
    nctId: "NCT05923847",
    title: "Targeted Therapy Study for EGFR-Mutant Lung Adenocarcinoma",
    sponsor: "Massachusetts General Hospital",
    phase: "Phase 2",
    status: "Recruiting",
    matchScore: 87,
    condition: "Non-Small Cell Lung Cancer",
    location: {
      city: "Boston",
      state: "MA",
      country: "USA",
      facility: "Massachusetts General Hospital Cancer Center",
      coordinates: { lat: 42.3631, lng: -71.0686 },
    },
    distance: "215 miles",
    eligibilityCriteria: {
      inclusion: [
        "Confirmed EGFR mutation",
        "Age 18-80 years",
        "Measurable disease per RECIST 1.1",
        "Life expectancy greater than 3 months",
      ],
      exclusion: [
        "Prior EGFR TKI therapy",
        "Uncontrolled hypertension",
        "Recent major surgery",
      ],
    },
    description:
      "A single-arm study evaluating the efficacy of next-generation EGFR inhibitor in treatment-naive patients with EGFR-mutant lung adenocarcinoma.",
    startDate: "2024-03-15",
    estimatedEndDate: "2027-03-15",
    enrollment: 180,
    primaryOutcome: "Objective response rate",
    contactInfo: {
      name: "Clinical Trials Office",
      phone: "(617) 726-2000",
      email: "mghtrialsinfo@partners.org",
    },
  },
  {
    id: "3",
    nctId: "NCT05738294",
    title: "Diabetes Management with Novel GLP-1 Receptor Agonist",
    sponsor: "Joslin Diabetes Center",
    phase: "Phase 3",
    status: "Recruiting",
    matchScore: 82,
    condition: "Type 2 Diabetes",
    location: {
      city: "Boston",
      state: "MA",
      country: "USA",
      facility: "Joslin Diabetes Center",
      coordinates: { lat: 42.3388, lng: -71.1067 },
    },
    distance: "220 miles",
    eligibilityCriteria: {
      inclusion: [
        "Type 2 diabetes diagnosed at least 6 months ago",
        "HbA1c between 7.5% and 10.5%",
        "BMI 25-40 kg/m2",
        "Stable metformin dose for 3 months",
      ],
      exclusion: [
        "Type 1 diabetes",
        "History of pancreatitis",
        "eGFR less than 30 mL/min",
        "Recent cardiovascular event",
      ],
    },
    description:
      "Evaluating a novel once-weekly GLP-1 receptor agonist for improved glycemic control and weight management in patients with type 2 diabetes.",
    startDate: "2024-01-01",
    estimatedEndDate: "2026-06-30",
    enrollment: 600,
    primaryOutcome: "Change in HbA1c from baseline at 52 weeks",
    contactInfo: {
      name: "Research Coordinator",
      phone: "(617) 309-2400",
      email: "research@joslin.harvard.edu",
    },
  },
  {
    id: "4",
    nctId: "NCT05629384",
    title: "Combination Immunotherapy for Advanced Solid Tumors",
    sponsor: "Johns Hopkins Sidney Kimmel Cancer Center",
    phase: "Phase 1",
    status: "Recruiting",
    matchScore: 76,
    condition: "Non-Small Cell Lung Cancer",
    location: {
      city: "Baltimore",
      state: "MD",
      country: "USA",
      facility: "Johns Hopkins Hospital",
      coordinates: { lat: 39.2965, lng: -76.5927 },
    },
    distance: "185 miles",
    eligibilityCriteria: {
      inclusion: [
        "Advanced solid tumor",
        "Failed at least one prior therapy",
        "Adequate bone marrow function",
      ],
      exclusion: [
        "Active infection",
        "Immunocompromised state",
        "Pregnancy or breastfeeding",
      ],
    },
    description:
      "First-in-human study of novel checkpoint inhibitor combination with dose escalation and expansion phases.",
    startDate: "2023-09-01",
    estimatedEndDate: "2025-12-31",
    enrollment: 90,
    primaryOutcome: "Maximum tolerated dose and safety profile",
    contactInfo: {
      name: "Cancer Clinical Trials Office",
      phone: "(410) 955-8804",
      email: "jhcccro@jhmi.edu",
    },
  },
  {
    id: "5",
    nctId: "NCT05847123",
    title: "Blood Pressure Control Study with Novel Antihypertensive",
    sponsor: "Cleveland Clinic",
    phase: "Phase 3",
    status: "Active",
    matchScore: 71,
    condition: "Hypertension",
    location: {
      city: "Cleveland",
      state: "OH",
      country: "USA",
      facility: "Cleveland Clinic Main Campus",
      coordinates: { lat: 41.5034, lng: -81.6214 },
    },
    distance: "450 miles",
    eligibilityCriteria: {
      inclusion: [
        "Essential hypertension",
        "Age 30-75 years",
        "Systolic BP 140-180 mmHg",
      ],
      exclusion: [
        "Secondary hypertension",
        "Severe renal impairment",
        "History of angioedema",
      ],
    },
    description:
      "Randomized controlled trial comparing novel antihypertensive agent to standard therapy for blood pressure management.",
    startDate: "2023-06-01",
    estimatedEndDate: "2025-06-01",
    enrollment: 800,
    primaryOutcome: "Mean change in systolic blood pressure at 12 weeks",
    contactInfo: {
      name: "Hypertension Research Team",
      phone: "(216) 444-2200",
      email: "htnclinicaltrial@ccf.org",
    },
  },
]

export const mockTreatments: Treatment[] = [
  {
    id: "1",
    name: "Pembrolizumab (Keytruda)",
    type: "medication",
    description:
      "Immune checkpoint inhibitor that helps the immune system fight cancer by blocking PD-1 protein.",
    effectiveness: 85,
    sideEffects: [
      "Fatigue",
      "Skin rash",
      "Nausea",
      "Decreased appetite",
      "Immune-related adverse events",
    ],
    contraindications: [
      "Active autoimmune disease",
      "Prior severe reaction to checkpoint inhibitors",
    ],
    averageCost: "$15,000-$20,000 per infusion",
    insuranceCoverage: "typically covered",
    duration: "30-minute infusion every 3 weeks",
    frequency: "Every 3 weeks for up to 2 years",
  },
  {
    id: "2",
    name: "Stereotactic Body Radiation Therapy (SBRT)",
    type: "procedure",
    description:
      "Highly precise radiation therapy that delivers high doses of radiation to tumors while minimizing damage to surrounding tissue.",
    effectiveness: 78,
    sideEffects: ["Fatigue", "Skin irritation", "Temporary breathing changes"],
    contraindications: [
      "Large tumor size",
      "Poor lung function",
      "Prior chest radiation",
    ],
    averageCost: "$20,000-$50,000 per course",
    insuranceCoverage: "typically covered",
    duration: "3-5 treatment sessions",
    frequency: "Daily sessions over 1-2 weeks",
  },
  {
    id: "3",
    name: "Metformin",
    type: "medication",
    description:
      "First-line medication for type 2 diabetes that reduces glucose production in the liver and improves insulin sensitivity.",
    effectiveness: 88,
    sideEffects: [
      "GI upset",
      "Nausea",
      "Diarrhea",
      "Vitamin B12 deficiency",
    ],
    contraindications: [
      "Severe kidney disease",
      "Liver disease",
      "Metabolic acidosis",
    ],
    averageCost: "$4-$20 per month",
    insuranceCoverage: "typically covered",
    duration: "Ongoing",
    frequency: "1-2 times daily with meals",
  },
  {
    id: "4",
    name: "Pulmonary Rehabilitation",
    type: "therapy",
    description:
      "Comprehensive program including exercise training, breathing techniques, and education to improve lung function and quality of life.",
    effectiveness: 72,
    sideEffects: ["Temporary muscle soreness", "Fatigue during initial sessions"],
    contraindications: [
      "Unstable cardiac conditions",
      "Severe mobility limitations",
    ],
    averageCost: "$1,500-$3,000 per program",
    insuranceCoverage: "typically covered",
    duration: "8-12 weeks",
    frequency: "2-3 sessions per week",
  },
  {
    id: "5",
    name: "Video-Assisted Thoracoscopic Surgery (VATS)",
    type: "surgery",
    description:
      "Minimally invasive surgical technique for lung cancer removal using small incisions and a camera.",
    effectiveness: 82,
    sideEffects: [
      "Post-operative pain",
      "Temporary shortness of breath",
      "Risk of infection",
    ],
    contraindications: [
      "Central tumor location",
      "Poor lung function",
      "Advanced disease",
    ],
    averageCost: "$40,000-$80,000",
    insuranceCoverage: "typically covered",
    duration: "2-4 hour procedure",
    frequency: "One-time procedure",
  },
]
